"""
Omniscope AI - Sectors 01 to 06 (133 Distinct Indian Companies)
Sectors:
  01. Automotive & Electric Mobility (22)
  02. Banking & Financial Institutions (22)
  03. FinTech, Payments & InsurTech (23)
  04. IT Services & Global Tech Consulting (22)
  05. Enterprise Software, Cloud & SaaS (22)
  06. Pharmaceuticals & Bulk APIs (22)
"""

SECTORS_01_06 = [
    # --- SECTOR 1: Automotive & Electric Mobility (22 companies) ---
    {
        "company": "Tata Motors Passenger Vehicles", "sector": "Automotive & Electric Mobility",
        "target_customer": "safety-conscious middle-class Indian families and modern urban commuters",
        "statement_of_need": "demand certified 5-star crash safety and reliable indigenous electric personal mobility",
        "product_name": "Nexon EV & Bharat NCAP 5-Star SUV Range", "product_category": "Electric & ICE Compact SUVs",
        "statement_of_key_benefit": "delivers certified 5-star structural crash safety, indigenous Ziptron EV powertrains, and extensive public charging ecosystem support",
        "pestle": {"political": 0.68, "economic": 0.72, "social": 0.85, "technological": 0.82, "legal": 0.65, "environmental": 0.88,
            "details": {"political": "Strong beneficiary of FAME-II, PM E-DRIVE, and Automotive PLI schemes; aligned with Ministry of Road Transport Bharat NCAP crash safety mandates.", "economic": "Exposed to automotive retail loan interest rate cycles and raw commodity swings (steel, lithium carbonate), offset by resilient domestic SUV demand.", "social": "Riding widespread societal shift prioritizing vehicle safety ratings over mere fuel efficiency, combined with high brand trust in the Tata conglomerate.", "technological": "Pioneered proprietary Ziptron high-voltage EV architecture, multi-mode regenerative braking, and in-house iRA connected vehicle telematics.", "legal": "Strictly adheres to BS-VI Phase 2 Real Driving Emissions (RDE), CAFÉ-II fleet emission targets, and AIS-156 EV battery pack safety certifications.", "environmental": "Accelerates zero tailpipe emission mobility across Tier-1/2 Indian cities, backed by closed-loop circular battery recycling initiatives."}},
        "porters": {"threat_of_new_entrants": 0.25, "bargaining_power_of_buyers": 0.75, "bargaining_power_of_suppliers": 0.68, "threat_of_substitutes": 0.40, "competitive_rivalry": 0.86,
            "details": {"threat_of_new_entrants": "Very low; multi-billion dollar manufacturing Capex, complex supply chains, and nationwide dealer networks form impenetrable entry moats.", "bargaining_power_of_buyers": "High; Indian car buyers actively cross-shop across Hyundai, Mahindra, and Kia with zero switching costs between showrooms.", "bargaining_power_of_suppliers": "Moderate-to-high; dependency on specialized lithium cell suppliers (Gotion, Tata AutoComp) and global automotive microcontrollers.", "threat_of_substitutes": "Moderate; metro rail expansions, electric two-wheelers, and ride-hailing services present alternatives in congested metros.", "competitive_rivalry": "Intense; continuous feature-war competition (panoramic sunroofs, Level-2 ADAS) and competitive pricing against domestic and global automakers."}}
    },
    {
        "company": "Maruti Suzuki India", "sector": "Automotive & Electric Mobility",
        "target_customer": "value-focused first-time Indian car buyers and budget-conscious suburban families",
        "statement_of_need": "require ultra-high fuel efficiency, rock-bottom maintenance costs, and ubiquitous nationwide service accessibility",
        "product_name": "Swift, Baleno & S-CNG Factory Lineup", "product_category": "Fuel-Efficient Hatchbacks & Factory CNG Vehicles",
        "statement_of_key_benefit": "provides unmatched 25-35 km/kg fuel economy, the widest pan-India service and spare parts network with 4,000+ workshops, and unbeatable resale value",
        "pestle": {"political": 0.62, "economic": 0.88, "social": 0.82, "technological": 0.68, "legal": 0.68, "environmental": 0.58,
            "details": {"political": "Engages with Ministry of Petroleum & Natural Gas on City Gas Distribution (CGD) expansion and GST Council debates on hybrid vehicle taxation.", "economic": "Directly exposed to fuel price inflation, rural monsoon harvest cash flows, and discretionary purchasing power of entry-level Indian households.", "social": "Entrenched as the quintessential Indian family car brand symbolizing mobility democratisation and peace of mind across non-metro towns.", "technological": "Engineering focuses on ultra-lightweight HEARTECT crash platforms, factory-integrated dual-interdependent S-CNG ECUs, and Smart Hybrid systems.", "legal": "Adapting to mandatory 6-airbag regulations, updated pedestrian crash standards, and mandatory corporate average fuel economy (CAFÉ) penalties.", "environmental": "Promotes compressed natural gas (CNG) and strong-hybrid propulsion as pragmatic, mass-scale carbon reduction pathways for developing India."}},
        "porters": {"threat_of_new_entrants": 0.20, "bargaining_power_of_buyers": 0.80, "bargaining_power_of_suppliers": 0.55, "threat_of_substitutes": 0.50, "competitive_rivalry": 0.88,
            "details": {"threat_of_new_entrants": "Extremely low; 40+ years of entrenched vendor clusters in Gurugram/Gujarat and 3,500+ sales touchpoints are impossible to replicate.", "bargaining_power_of_buyers": "High; entry-segment buyers are hyper-sensitive to price differences of even ₹10,000-20,000 and easily compare financing schemes.", "bargaining_power_of_suppliers": "Low-to-moderate; Maruti commands immense supplier pricing leverage due to sheer 1.8M+ annual vehicle production volumes.", "threat_of_substitutes": "Moderate; public transit, pre-owned cars, two-wheelers, and electric three-wheelers compete for entry-level wallet share.", "competitive_rivalry": "Fierce; battling Hyundai, Tata Motors, and compact SUV crossover entrants encroaching into traditional hatchback territory."}}
    },
    {
        "company": "Mahindra & Mahindra Automotive", "sector": "Automotive & Electric Mobility",
        "target_customer": "lifestyle adventure enthusiasts, rural landowners, and aspirational executive SUV buyers",
        "statement_of_need": "seek commanding high-seating road presence, rugged ladder-frame 4x4 off-road durability, and authentic butch SUV styling",
        "product_name": "Scorpio-N, Thar 4x4 & XUV700", "product_category": "Authentic Body-on-Frame & Monocoque Performance SUVs",
        "statement_of_key_benefit": "delivers legendary 4x4 go-anywhere off-road capability, potent mStallion turbo-petrol and mHawk diesel powertrains, and commanding road dominance",
        "pestle": {"political": 0.65, "economic": 0.74, "social": 0.86, "technological": 0.78, "legal": 0.64, "environmental": 0.60,
            "details": {"political": "Benefits from defense vehicle procurement contracts and indigenous manufacturing incentives, while navigating diesel vehicle regulatory restrictions.", "economic": "Strongly cushioned by dual rural-urban exposure, capturing both agricultural tractor/utility demand and affluent metro lifestyle SUV booms.", "social": "Capitalizes on deep-rooted cultural affinity for imposing SUV road presence, leisure road-tripping, and weekend overland expedition clubs.", "technological": "Developed high-output mHawk aluminium diesel engines, mStallion TGDi turbo-petrols, AdrenoX smart vehicle OS, and custom 4XPLOR terrain modes.", "legal": "Subject to National Green Tribunal (NGT) diesel lifespan caps in Delhi-NCR, stringent BS-VI Stage 2 SCR emissions, and RERA/factory safety compliances.", "environmental": "Investing ₹10,000+ Cr in dedicated born-electric INGLO EV architecture in Chakan to transition iconic SUV DNA into zero-carbon mobility."}},
        "porters": {"threat_of_new_entrants": 0.22, "bargaining_power_of_buyers": 0.65, "bargaining_power_of_suppliers": 0.62, "threat_of_substitutes": 0.35, "competitive_rivalry": 0.82,
            "details": {"threat_of_new_entrants": "Low; developing heavy-duty ladder-frame tooling, homologation, and durable 4x4 transfer cases requires deep specialized engineering.", "bargaining_power_of_buyers": "Moderate; cult-like emotional appeal and year-long waiting lists for Thar and Scorpio-N grant Mahindra significant pricing power.", "bargaining_power_of_suppliers": "Moderate; relies on specialized 4WD drivetrain vendors (BorgWarner, Dana) and high-tensile steel fabricators.", "threat_of_substitutes": "Low-to-moderate; rugged off-road recreation and rough rural terrain have virtually zero alternatives besides utility pickups.", "competitive_rivalry": "High; competes directly with Tata Safari/Harrier, Force Gurkha, Toyota Fortuner, and mid-size monocoque crossovers."}}
    },
    {
        "company": "Royal Enfield (Eicher Motors)", "sector": "Automotive & Electric Mobility",
        "target_customer": "leisure motorcyclists, highway touring enthusiasts, and heritage lifestyle riders",
        "statement_of_need": "desire an authentic, thumping retro roadster aesthetic, relaxed long-distance riding posture, and camaraderie in an iconic riding brotherhood",
        "product_name": "Classic 350, Hunter & Himalayan 450", "product_category": "Middleweight Heritage & Adventure Motorcycles",
        "statement_of_key_benefit": "delivers the unmistakable exhaust beat of the refined J-series single-cylinder engine, timeless vintage British-Indian styling, and access to global riding communities",
        "pestle": {"political": 0.58, "economic": 0.70, "social": 0.90, "technological": 0.72, "legal": 0.62, "environmental": 0.55,
            "details": {"political": "Leverages Make in India export incentives to ship Chennai-manufactured middleweight motorcycles across Europe, North America, and LatAm.", "economic": "Thrives on discretionary premiumization in urban and Tier-2 India where upwardly mobile youth graduate from 100cc commuters to lifestyle leisure bikes.", "social": "World's oldest motorcycle brand in continuous production with intense cult fandom, annual Rider Mania festivals, and Himalayan expedition culture.", "technological": "Modernized J-series and Sherpa 450 liquid-cooled DOHC engines balance heritage character with electronic counter-balancers and Tripper navigation.", "legal": "Complies with strict decibel emission limits, dual-channel ABS mandates, and Euro-5+ / BS-VI Phase 2 onboard diagnostic standards.", "environmental": "Developing electric motorcycle prototypes under the Flying Flea sub-brand while optimizing waterless manufacturing plants in Oragadam."}},
        "porters": {"threat_of_new_entrants": 0.28, "bargaining_power_of_buyers": 0.58, "bargaining_power_of_suppliers": 0.55, "threat_of_substitutes": 0.42, "competitive_rivalry": 0.80,
            "details": {"threat_of_new_entrants": "Moderate-low; competitors like Honda (H'ness CB350), Triumph, and Harley-Davidson have attempted entry, but matching Enfield's soul is difficult.", "bargaining_power_of_buyers": "Moderate; customers exhibit fierce emotional brand loyalty and readily customize their motorcycles with OEM touring accessories.", "bargaining_power_of_suppliers": "Moderate; strong local supplier base in Tamil Nadu auto corridor (Gabriel, Endurance, Minda) ensures cost containment.", "threat_of_substitutes": "Moderate; sport bikes (KTM, Yamaha) and mid-range naked streetfighters attract younger demographic segments seeking raw speed.", "competitive_rivalry": "Intense; global partnerships (Bajaj-Triumph, Hero-Harley) specifically target Royal Enfield's 75%+ monopoly in the 250cc-750cc segment."}}
    },
    {
        "company": "Ather Energy", "sector": "Automotive & Electric Mobility",
        "target_customer": "tech-savvy urban millennials, design purists, and premium eco-commuters",
        "statement_of_need": "seek a precision-engineered, connected electric scooter with sports car-like acceleration, predictive Google Maps navigation, and zero thermal degradation",
        "product_name": "Ather 450X & Rizta Family Scooter", "product_category": "Smart Premium Electric Scooters",
        "statement_of_key_benefit": "features an all-aluminum hybrid chassis, instantaneous 3.3-second 0-40 km/h Warp mode, Google-powered touchscreen dashboard with AutoHold, and Ather Grid fast charging",
        "pestle": {"political": 0.72, "economic": 0.68, "social": 0.84, "technological": 0.92, "legal": 0.65, "environmental": 0.90,
            "details": {"political": "Actively participates in Bureau of Indian Standards (BIS) interoperable light EV charging connector standard formulation and EMPS subsidy schemes.", "economic": "Targeting premium urban consumers willing to pay an upfront capital premium for significantly reduced operational running costs per kilometer.", "social": "Appeals to affluent early adopters who view electric mobility as a statement of design refinement, software intelligence, and environmental mindfulness.", "technological": "Pioneered proprietary AtherStack Linux-based vehicle OS, Google Maps dashboard integration, coasting regen algorithms, and fast-charging algorithms.", "legal": "Meets AIS-156 Amendment 3 strict battery thermal runaway standards, consumer protection warranty disclosures, and DPDP connected telematics laws.", "environmental": "Eliminates tailpipe toxic NOx and particulate emissions in congested Indian metros, utilizing IP67 waterproof aluminum-encased battery packs."}},
        "porters": {"threat_of_new_entrants": 0.40, "bargaining_power_of_buyers": 0.70, "bargaining_power_of_suppliers": 0.72, "threat_of_substitutes": 0.52, "competitive_rivalry": 0.85,
            "details": {"threat_of_new_entrants": "Moderate; numerous venture-funded EV startups attempt market entry, but building safe thermal management and dealer networks is challenging.", "bargaining_power_of_buyers": "High; urban consumers compare range, charging times, boot space, and upfront sticker prices across Ola, TVS iQube, and Bajaj Chetak.", "bargaining_power_of_suppliers": "High; dependent on international cell vendors (CATL, Samsung SDI) and specialized high-speed automotive grade processors.", "threat_of_substitutes": "High; traditional petrol scooters (Honda Activa, TVS Jupiter) still dominate 85%+ of overall two-wheeler retail volumes.", "competitive_rivalry": "Fierce; engaging in aggressive showroom expansion, price cuts, and warranty wars against deep-pocketed legacy OEMs and Ola Electric."}}
    },
    {
        "company": "Ola Electric Mobility", "sector": "Automotive & Electric Mobility",
        "target_customer": "mass-market suburban commuters and budget-conscious daily college riders",
        "statement_of_need": "need hyper-affordable electric two-wheeler mobility with industry-leading battery range and aggressive digital pricing",
        "product_name": "Ola S1 Pro & S1 X Generation 2", "product_category": "Mass-Market Electric Two-Wheelers",
        "statement_of_key_benefit": "delivers high 190 km IDC certified battery range, 11 kW peak motor output, direct-to-home online delivery, and upcoming proprietary Bharat 4680 cell integration",
        "pestle": {"political": 0.75, "economic": 0.78, "social": 0.80, "technological": 0.88, "legal": 0.70, "environmental": 0.88,
            "details": {"political": "Leading recipient of Advanced Chemistry Cell (ACC) Battery PLI scheme subsidies, driving large-scale indigenous battery cell gigafactory setup in Tamil Nadu.", "economic": "Employs predatory price-disruption strategies to undercut Japanese petrol commuter two-wheelers and drive mass electrification adoption.", "social": "Captures youthful digital-first consumers attracted by hyper-modern minimalist aesthetics, digital smartphone unlocking, and Party Mode features.", "technological": "Developing indigenous 4680 cylindrical battery cells at the Ola Gigafactory and MoveOS multi-profile operating software.", "legal": "Facing intense scrutiny from Central Consumer Protection Authority (CCPA) over after-sales service delays, warranty claims, and showroom SLA compliances.", "environmental": "Accelerates zero-emission mass transit transition across India, reducing suburban reliance on imported fossil crude oil."}},
        "porters": {"threat_of_new_entrants": 0.35, "bargaining_power_of_buyers": 0.78, "bargaining_power_of_suppliers": 0.60, "threat_of_substitutes": 0.55, "competitive_rivalry": 0.90,
            "details": {"threat_of_new_entrants": "Moderate-low; massive gigafactory scale, automated mega-factory robotics, and direct D2C logistics create substantial barrier for newcomers.", "bargaining_power_of_buyers": "High; consumers are vocal on social platforms regarding service turnaround times and readily switch to legacy brands (TVS, Bajaj).", "bargaining_power_of_suppliers": "Moderate; heavy backward integration into software, chassis stamping, and upcoming in-house cell manufacturing mitigates vendor squeeze.", "threat_of_substitutes": "High; widespread availability of proven ICE scooters (Hero, Honda) that require zero charging planning.", "competitive_rivalry": "Extreme; waging high-stakes market share battles against TVS iQube, Bajaj Chetak, and Ather Energy across all state capitals."}}
    },
    {
        "company": "Bajaj Auto", "sector": "Automotive & Electric Mobility",
        "target_customer": "aggressive performance youth riders and global export two-wheeler buyers",
        "statement_of_need": "demand pulse-racing street naked acceleration, muscular styling, and bulletproof mechanical reliability",
        "product_name": "Pulsar & Dominar Sports Lineup", "product_category": "Performance Street Motorcycles",
        "statement_of_key_benefit": "features patented DTS-i twin/triple spark liquid-cooled engines, perimeter frame handling, and engineering export presence across 70+ countries",
        "pestle": {"political": 0.60, "economic": 0.72, "social": 0.82, "technological": 0.75, "legal": 0.62, "environmental": 0.62,
            "details": {"political": "Benefits from foreign trade policy export duty drawdowns and bilateral export agreements into Africa, Southeast Asia, and Latin America.", "economic": "Hedging domestic demand cycles with significant foreign exchange earnings from two-wheeler and three-wheeler exports worldwide.", "social": "Created the 'Definitely Male' sports motorcycling craze in India, embedding Pulsar as an enduring status symbol for young aspirational men.", "technological": "Partnerships with KTM, Husqvarna, and Triumph (Speed 400) allow cross-pollination of precision liquid-cooled engineering and ride-by-wire.", "legal": "Complies with global homologation standards, dual-channel anti-lock braking regulations, and BS-VI onboard diagnostic monitoring.", "environmental": "Reviving the Chetak brand in an elegant all-metal electric avatar and pioneering the world's first mass-production CNG motorcycle (Freedom 125)."}},
        "porters": {"threat_of_new_entrants": 0.25, "bargaining_power_of_buyers": 0.70, "bargaining_power_of_suppliers": 0.58, "threat_of_substitutes": 0.45, "competitive_rivalry": 0.85,
            "details": {"threat_of_new_entrants": "Low; establishing massive 5-million vehicle manufacturing capacity and global distribution in 70 countries takes decades.", "bargaining_power_of_buyers": "Moderate-high; youthful buyers demand constant cosmetic updates, USD forks, and Bluetooth connectivity before committing funds.", "bargaining_power_of_suppliers": "Low-to-moderate; long-standing vendor relationships in the Chakan auto-belt ensure low component costs and reliable delivery.", "threat_of_substitutes": "Moderate; lifestyle retro roadsters (Royal Enfield) and entry-level electric bikes compete for youth transportation budgets.", "competitive_rivalry": "High; engaged in intense horsepower battles against TVS Apache, Yamaha MT-15, and Honda Hornet."}}
    },
    {
        "company": "TVS Motor Company", "sector": "Automotive & Electric Mobility",
        "target_customer": "racing track enthusiasts and discerning urban commuters",
        "statement_of_need": "seek racing-derived high-rpm throttle response, razor-sharp chassis cornering, and connected smartphone telemetry",
        "product_name": "Apache RTR & iQube Electric Series", "product_category": "Track-Tuned Motorcycles & Smart Electric Scooters",
        "statement_of_key_benefit": "delivers race-tuned fuel injection (RT-FI), SmartXonnect Bluetooth race telemetry with lean angle displays, and reliable build quality",
        "pestle": {"political": 0.62, "economic": 0.70, "social": 0.82, "technological": 0.84, "legal": 0.64, "environmental": 0.75,
            "details": {"political": "Participates in government EV incentive programs and co-develops small-displacement motorcycles with BMW Motorrad under Make in India.", "economic": "Strong multi-segment revenue streams balancing commuter scooters (Jupiter), high-margin sports bikes (Apache), and electric two-wheelers.", "social": "Deep roots in competitive motorsport through TVS Racing, India's oldest factory racing team, fostering a passionate youth racing fanbase.", "technological": "Engineering excellence with race-tuned slipper clutches, adjustable Showa suspension, riding modes (Rain, Urban, Sport), and connected clusters.", "legal": "Compliance with AIS battery safety rules, automated lighting regulations, and European UNECE safety norms for export vehicles.", "environmental": "Accelerating transition to clean transport through the successful TVS iQube electric scooter and acquiring iconic British brand Norton to engineer EV superbikes."}},
        "porters": {"threat_of_new_entrants": 0.26, "bargaining_power_of_buyers": 0.72, "bargaining_power_of_suppliers": 0.58, "threat_of_substitutes": 0.46, "competitive_rivalry": 0.85,
            "details": {"threat_of_new_entrants": "Low; R&D capabilities, wind tunnel testing facilities in Hosur, and 1,000+ dealership networks protect incumbent position.", "bargaining_power_of_buyers": "Moderate-high; customers can choose between Bajaj Pulsar, Yamaha, and Ather across sports and electric categories.", "bargaining_power_of_suppliers": "Moderate; balanced supply chain network with specialized electronics suppliers for digital TFT dashboards.", "threat_of_substitutes": "Moderate; public transit and shared ride platforms offer everyday transportation alternatives.", "competitive_rivalry": "Intense; battling head-to-head with Bajaj in 160-310cc motorcycles and with Ather/Ola in electric scooters."}}
    },
    {
        "company": "Hero MotoCorp", "sector": "Automotive & Electric Mobility",
        "target_customer": "rural agrarian workers, small traders, and suburban daily commuters",
        "statement_of_need": "need indestructible everyday reliability, ultra-affordable maintenance, and 65+ kmpl fuel economy on rough rural terrain",
        "product_name": "Splendor Plus & VIDA V1 Electric", "product_category": "High-Utility Commuter Motorcycles & Emerging EVs",
        "statement_of_key_benefit": "provides iconic fuel-saving i3S start-stop technology, unmatched rural spare parts availability across every Indian tehsil, and high durability",
        "pestle": {"political": 0.60, "economic": 0.86, "social": 0.84, "technological": 0.65, "legal": 0.62, "environmental": 0.58,
            "details": {"political": "Subject to state agricultural support programs, rural credit schemes, and Bharat Stage VI onboard diagnostic compliance.", "economic": "Direct barometer of the Indian rural agrarian economy, monsoon rainfall patterns, and Kharif-Rabi harvest cash liquidity.", "social": "Splendor is India's most trusted two-wheeler nameplate for 30+ years, regarded as a reliable family livelihood tool.", "technological": "Proprietary i3S idle start-stop system, xSens intelligent fuel injection sensors, and modular VIDA swappable battery tech.", "legal": "Complies with compulsory combined braking systems (IBS) and mandatory vehicle scrappage policy guidelines.", "environmental": "Transitioning fleet towards green mobility via VIDA electric scooter brand and investing in Ather Energy charging infrastructure."}},
        "porters": {"threat_of_new_entrants": 0.18, "bargaining_power_of_buyers": 0.78, "bargaining_power_of_suppliers": 0.52, "threat_of_substitutes": 0.50, "competitive_rivalry": 0.84,
            "details": {"threat_of_new_entrants": "Extremely low; over 9,000 dealerships and rural customer touchpoints represent an unassailable distribution fortress.", "bargaining_power_of_buyers": "High; rural buyers are extremely price-conscious, comparing financing rates and exchange bonus schemes.", "bargaining_power_of_suppliers": "Low; Hero exerts massive procurement power over auto-component vendors in Haridwar, Dharuhera, and Halol.", "threat_of_substitutes": "Moderate; regional state-run bus transit, rural train lines, and pre-owned motorcycles offer mobility alternatives.", "competitive_rivalry": "High; defending mass commuter market share against Honda (Shine 100) and Bajaj Platina."}}
    },
    {
        "company": "Ashok Leyland (Hinduja Group)", "sector": "Automotive & Electric Mobility",
        "target_customer": "heavy commercial transport operators, mining haulage firms, and logistics fleet owners",
        "statement_of_need": "require heavy payload reliability, maximum uptime, and low operational cost per ton-kilometer across Indian national highways",
        "product_name": "AVTR Modular Truck Platform & Dost LCV", "product_category": "Medium & Heavy Commercial Vehicles (M&HCV)",
        "statement_of_key_benefit": "features India's first modular truck architecture with i-Gen6 mid-NOx engine technology, Leykart digital parts, and i-Alert 24/7 telematics",
        "pestle": {"political": 0.70, "economic": 0.85, "social": 0.68, "technological": 0.78, "legal": 0.72, "environmental": 0.70,
            "details": {"political": "Direct beneficiary of PM Gati Shakti national infrastructure investments, dedicated freight corridors, and mandatory AC truck cabin rules.", "economic": "Highly cyclical performance intrinsically tied to national GDP growth, industrial manufacturing output, and mining activity.", "social": "Addresses truck driver welfare through modern ergonomic air-conditioned cabins and pan-India highway driver training institutes.", "technological": "Indigenous i-Gen6 engine technology optimizes diesel exhaust fluid consumption without complex EGR; i-Alert IoT fleet telematics.", "legal": "Adheres to strict axle-load norms, central motor vehicle rules (CMVR), and AIS-029 truck cab crashworthiness standards.", "environmental": "Pioneering commercial hydrogen ICE engine trucks, LNG-powered heavy trucks, and Switch Mobility electric commercial buses."}},
        "porters": {"threat_of_new_entrants": 0.20, "bargaining_power_of_buyers": 0.72, "bargaining_power_of_suppliers": 0.62, "threat_of_substitutes": 0.45, "competitive_rivalry": 0.82,
            "details": {"threat_of_new_entrants": "Very low; multi-crore testing facilities, specialized foundry casting, and nationwide commercial service workshops create steep barriers.", "bargaining_power_of_buyers": "High; fleet operators managing hundreds of trucks negotiate aggressive volume fleet discounts and buyback terms.", "bargaining_power_of_suppliers": "Moderate; dependency on specialized fuel-injection suppliers (Bosch) and heavy axle forgings.", "threat_of_substitutes": "Moderate; Dedicated Freight Corridor (DFC) rail cargo movement competes on long-distance bulk freight routes.", "competitive_rivalry": "Intense duopoly rivalry against Tata Motors Commercial Vehicles, alongside competition from VE Commercial Vehicles (Volvo-Eicher)."}}
    },
    {
        "company": "Force Motors", "sector": "Automotive & Electric Mobility",
        "target_customer": "shared rural passenger operators, emergency healthcare fleets, and extreme off-road enthusiasts",
        "statement_of_need": "need high-capacity rugged van utility, specialized ambulance chassis, or mechanical locking differential off-road capability",
        "product_name": "Trax Cruiser, Traveller & Gurkha 4x4", "product_category": "Specialized Utility Vehicles & Off-Road Platforms",
        "statement_of_key_benefit": "provides proven Mercedes-derived engine architecture, heavy-duty mechanical locking front/rear differentials, and versatile multi-passenger chassis",
        "pestle": {"political": 0.62, "economic": 0.75, "social": 0.78, "technological": 0.65, "legal": 0.68, "environmental": 0.55,
            "details": {"political": "Supplies government hospital emergency ambulance fleets under National Health Mission (NHM) procurement tenders.", "economic": "Driven by rural collective transportation demand where 10-13 passenger Trax vehicles provide vital lifeline transit between remote villages and mandi towns.", "social": "Recognized as the gold standard for life-saving ambulances, school buses, and shared passenger vans across India.", "technological": "Manufactures precision engines and axles under long-standing technical alliances for luxury automotive brands like Mercedes-Benz and BMW.", "legal": "Complies with stringent National Ambulance Code (AIS-125) standards, rollover crash regulations, and BS-VI emissions.", "environmental": "Developing electric Traveller variants for intra-city school bus fleets and zero-emission urban delivery runs."}},
        "porters": {"threat_of_new_entrants": 0.22, "bargaining_power_of_buyers": 0.65, "bargaining_power_of_suppliers": 0.60, "threat_of_substitutes": 0.38, "competitive_rivalry": 0.75,
            "details": {"threat_of_new_entrants": "Low; dominant 70%+ market monopoly in monocoque panel vans (Traveller) with specialized tooling makes entry difficult.", "bargaining_power_of_buyers": "Moderate; ambulance operators and tour agencies have limited alternatives offering the spacious head-room of the Traveller.", "bargaining_power_of_suppliers": "Moderate; reliant on Mercedes-derived tooling and specialized stamping dies.", "threat_of_substitutes": "Moderate; Mahindra Bolero and bus chassis compete in shared rural transport sectors.", "competitive_rivalry": "Moderate-high; Gurkha competes against Mahindra Thar, while Traveller competes with Tata Winger."}}
    },
    {
        "company": "Olectra Greentech", "sector": "Automotive & Electric Mobility",
        "target_customer": "state transport undertakings (STUs) and municipal smart city transit authorities",
        "statement_of_need": "require zero-emission, silent electric city transit buses with low operating lifecycle costs and reliable battery fast-charging",
        "product_name": "K9 & K6 Electric Transit Buses", "product_category": "Commercial Electric City Buses",
        "statement_of_key_benefit": "features proven lithium iron phosphate (LFP) chemistry batteries, regenerative braking, regenerative roof charging, and quiet passenger comfort",
        "pestle": {"political": 0.82, "economic": 0.70, "social": 0.80, "technological": 0.82, "legal": 0.70, "environmental": 0.95,
            "details": {"political": "Major beneficiary of FAME-II municipal electric bus tenders and PM-eBus Sewa initiative deploying 10,000 electric buses nationwide.", "economic": "Secures steady cash flows via Gross Cost Contract (GCC) models where state governments pay per-kilometer operational fees.", "social": "Improves public health by drastically slashing urban air pollution and diesel soot in major metropolitan centers like Mumbai, Pune, and Surat.", "technological": "Technical partnership with global EV pioneer BYD enables advanced battery management systems (BMS) and high-torque in-wheel electric motors.", "legal": "Complies with Central Motor Vehicle Rules (CMVR) for public transport, disabled-friendly low-floor access, and AIS battery guidelines.", "environmental": "Delivers zero direct tailpipe carbon emissions, contributing directly to India's COP26 climate goals and cleaner urban airsheds."}},
        "porters": {"threat_of_new_entrants": 0.30, "bargaining_power_of_buyers": 0.82, "bargaining_power_of_suppliers": 0.75, "threat_of_substitutes": 0.40, "competitive_rivalry": 0.84,
            "details": {"threat_of_new_entrants": "Moderate-low; state transport tender eligibility requires proven million-kilometer operational track record and massive bank guarantees.", "bargaining_power_of_buyers": "Very high; municipal transport corporations dictate stringent tender pricing, penalty clauses, and delivery timelines.", "bargaining_power_of_suppliers": "High; reliance on battery cell imports and motor electronics from BYD.", "threat_of_substitutes": "Moderate; CNG buses and diesel city transit buses remain legacy alternatives in non-electrified depots.", "competitive_rivalry": "Intense; competing in multi-thousand unit government tenders against Tata Motors, JBM Auto, and Ashok Leyland Switch."}}
    },
    {
        "company": "Greaves Cotton (Ampere Electric)", "sector": "Automotive & Electric Mobility",
        "target_customer": "Tier-2/3 budget commuters and gig delivery riders",
        "statement_of_need": "seek practical, affordable electric scooters and cargo 3-wheelers with low purchase barrier and quick payback",
        "product_name": "Ampere Nexus & Greaves 3W EV", "product_category": "Affordable Electric Two & Three Wheelers",
        "statement_of_key_benefit": "provides dependable LFP battery packs, comfortable dual suspension, and access to Greaves Care multi-brand service footprint across 400+ towns",
        "pestle": {"political": 0.70, "economic": 0.82, "social": 0.78, "technological": 0.74, "legal": 0.65, "environmental": 0.85,
            "details": {"political": "Aligns with state-level EV adoption policies offering road tax exemptions and registration subsidies for clean commercial vehicles.", "economic": "Addresses acute sensitivity to fuel inflation among gig economy delivery workers and semi-urban families seeking under-₹1 lakh EV options.", "social": "Enables micro-entrepreneurship for auto-rickshaw drivers and delivery partners via affordable monthly financing schemes.", "technological": "Engineering focuses on robust water-resistant IP67 powertrains, dual-battery swap compatibility, and high-efficiency permanent magnet motors.", "legal": "Complies with AIS-156 EV safety certifications, motor vehicle registration laws, and gig-worker commercial vehicle norms.", "environmental": "Displaces highly polluting 2-stroke and diesel commercial three-wheelers in semi-urban India with zero-emission electric drivetrains."}},
        "porters": {"threat_of_new_entrants": 0.42, "bargaining_power_of_buyers": 0.78, "bargaining_power_of_suppliers": 0.68, "threat_of_substitutes": 0.55, "competitive_rivalry": 0.82,
            "details": {"threat_of_new_entrants": "Moderate; low-speed and budget EV segments see frequent startup entrants, but long-term brand survival requires service backup.", "bargaining_power_of_buyers": "High; gig workers calculate daily running cost down to the rupee and switch to whichever brand offers cheapest financing.", "bargaining_power_of_suppliers": "Moderate-high; requires reliable supply of batteries and controllers from domestic and Asian component makers.", "threat_of_substitutes": "High; used ICE scooters and traditional petrol 3-wheelers provide immediate alternatives.", "competitive_rivalry": "Intense; fighting for market share against Hero Electric, Okinawa, Piaggio, and Euler Motors."}}
    },
    {
        "company": "Sonalika Tractors (International Tractors)", "sector": "Automotive & Electric Mobility",
        "target_customer": "progressive Indian farmers and custom agricultural hiring operators",
        "statement_of_need": "need high-torque, fuel-efficient farm tractors engineered for tough soil conditions and heavy multi-crop implements",
        "product_name": "Sonalika Tiger & Sikander Series", "product_category": "Customized High-Torque Agricultural Tractors",
        "statement_of_key_benefit": "features fuel-efficient heavy-duty CRDS engines, customized gear speeds for specific crop implements, and rapid 3-point hitch hydraulics",
        "pestle": {"political": 0.70, "economic": 0.84, "social": 0.85, "technological": 0.72, "legal": 0.62, "environmental": 0.60,
            "details": {"political": "Direct beneficiary of government agricultural mechanization subsidies, direct benefit transfer (DBT) farm equipment schemes, and Kisan credit.", "economic": "Directly dependent on rural farm liquidity, MSP (Minimum Support Price) procurement payouts, and monsoon agricultural yields.", "social": "Deeply embedded in the agrarian fabric of Punjab, Haryana, UP, and central India as a premier engine of farm prosperity.", "technological": "World's largest integrated tractor manufacturing plant in Hoshiarpur, producing next-gen Common Rail Diesel System (CRDS) Trem-IV farm engines.", "legal": "Meets Trem Stage IV agricultural tractor emission norms and central safety regulations for roll-over protection structures (ROPS).", "environmental": "Introduced the Sonalika Tiger Electric tractor, exploring zero-emission farming and reduced diesel reliance on rural farm estates."}},
        "porters": {"threat_of_new_entrants": 0.18, "bargaining_power_of_buyers": 0.68, "bargaining_power_of_suppliers": 0.55, "threat_of_substitutes": 0.35, "competitive_rivalry": 0.82,
            "details": {"threat_of_new_entrants": "Extremely low; heavy capital investment in engine foundries, transmission machining, and deep rural dealer credit networks.", "bargaining_power_of_buyers": "Moderate-high; farmers compare pulling power, PTO horsepower, and dealer trade-in values across Mahindra, John Deere, and Escorts.", "bargaining_power_of_suppliers": "Low-to-moderate; high internal backward integration in castings, sheet metal, and gearing minimizes vendor pricing pressure.", "threat_of_substitutes": "Low; mechanized farming implements require tractor PTO horsepower with no feasible manual substitute.", "competitive_rivalry": "Fierce; competing neck-and-neck against market leader Mahindra Tractors, TAFE, and John Deere India."}}
    },
    {
        "company": "Escorts Kubota Limited", "sector": "Automotive & Electric Mobility",
        "target_customer": "commercial mechanized farmers and railway engineering contractors",
        "statement_of_need": "seek Japanese precision engineering, automated paddy transplanting, and reliable infrastructure railway shock absorbers",
        "product_name": "Farmtrac, Powertrac & Kubota Agri Machinery", "product_category": "Precision Agri Tractors & Railway Brake Systems",
        "statement_of_key_benefit": "combines rugged Indian durability with Kubota Japanese precision engineering, automated 4WD puddle farming, and railway engineering components",
        "pestle": {"political": 0.65, "economic": 0.78, "social": 0.80, "technological": 0.82, "legal": 0.65, "environmental": 0.65,
            "details": {"political": "Strategic partnership with Japan's Kubota Corporation aligns with Indo-Japanese bilateral trade and Make in India high-tech manufacturing.", "economic": "Diversified business lines balancing agricultural tractor demand cycles with Indian Railways capital expenditure on Vande Bharat trains.", "social": "Empowers high-yield horticulture and paddy farmers through modern mechanization, reducing arduous physical farm labor.", "technological": "Deploys Japanese hydrostatic transmissions, automated paddy transplanters, high-speed rail brake discs, and electric tractor prototypes.", "legal": "Complies with Research Designs and Standards Organisation (RDSO) railway safety guidelines and Trem IV/V tractor emissions.", "environmental": "Pioneering precision farming technologies that minimize chemical runoff, optimize water usage in paddy fields, and reduce soil compaction."}},
        "porters": {"threat_of_new_entrants": 0.20, "bargaining_power_of_buyers": 0.68, "bargaining_power_of_suppliers": 0.58, "threat_of_substitutes": 0.36, "competitive_rivalry": 0.80,
            "details": {"threat_of_new_entrants": "Low; complex technical homologation for railway safety equipment and agricultural transmission plants create steep entry moats.", "bargaining_power_of_buyers": "Moderate; progressive farmers demand high-efficiency 4WD tractors and value Kubota's proven Japanese mechanical reliability.", "bargaining_power_of_suppliers": "Moderate; global sourcing of advanced Japanese hydraulic valves balanced by local Faridabad component casting.", "threat_of_substitutes": "Low; mechanized farm operations and railway braking systems have virtually no viable alternatives.", "competitive_rivalry": "High; competes with Mahindra, Sonalika, and John Deere in agriculture, and Knorr-Bremse in railway equipment."}}
    },
    {
        "company": "Kinetic Green Energy & Power Solutions", "sector": "Automotive & Electric Mobility",
        "target_customer": "urban passenger auto operators and municipal waste management departments",
        "statement_of_need": "need zero-emission electric 3-wheelers and mini utility vehicles with low upfront operating costs and reliable battery swap options",
        "product_name": "Kinetic Safar Smart & Safar Jumbo", "product_category": "Electric 3-Wheelers & Municipal Utility Vehicles",
        "statement_of_key_benefit": "provides sturdy steel chassis construction, high hill-climb gradability, fast battery swapping, and customized municipal waste tipping bodies",
        "pestle": {"political": 0.72, "economic": 0.80, "social": 0.82, "technological": 0.76, "legal": 0.66, "environmental": 0.90,
            "details": {"political": "Benefits from municipal smart city procurement tenders under the Swachh Bharat Mission for door-to-door electric waste collection.", "economic": "Significantly boosts the daily take-home earnings of auto-rickshaw drivers by cutting daily fuel spend from ₹400 (CNG/petrol) to ₹60 (electricity).", "social": "Fosters financial independence for urban transport operators transitioning from manual or pedal rickshaws to dignified electric mobility.", "technological": "Engineered high-torque dual-speed gearboxes for steep urban flyovers, battery swapping alliances, and telematics-connected battery monitors.", "legal": "Adheres to central AIS-156 safety standards for EV powertrains, local RTO registration norms, and municipal contractor compliance.", "environmental": "Drives zero-emission municipal garbage collection and replaces smoke-spewing two-stroke auto-rickshaws across Indian cities."}},
        "porters": {"threat_of_new_entrants": 0.38, "bargaining_power_of_buyers": 0.75, "bargaining_power_of_suppliers": 0.65, "threat_of_substitutes": 0.48, "competitive_rivalry": 0.80,
            "details": {"threat_of_new_entrants": "Moderate; while many unorganized players assemble uncertified e-rickshaws, organized fleet operators mandate certified brands like Kinetic.", "bargaining_power_of_buyers": "High; auto drivers and logistics companies demand tight financing terms, battery replacement warranties, and high trade-in value.", "bargaining_power_of_suppliers": "Moderate; reliant on battery pack fabricators and specialized electric motor suppliers.", "threat_of_substitutes": "Moderate; CNG auto-rickshaws (Bajaj, Piaggio) maintain widespread presence with instant refueling.", "competitive_rivalry": "Intense; competing directly with Mahindra Last Mile Mobility, Bajaj RE Electric, and Piaggio Ape Electrik."}}
    },
    {
        "company": "Piaggio Vehicles India", "sector": "Automotive & Electric Mobility",
        "target_customer": "intra-city commercial goods transporters and last-mile passenger auto drivers",
        "statement_of_need": "seek iconic high-payload 3-wheeler commercial cargo haulage with proven Italian engineering and multi-fuel (Diesel, CNG, Electric) flexibility",
        "product_name": "Ape City, Ape Xtra LDX & Ape Electrik", "product_category": "Commercial 3-Wheelers & Cargo Transporters",
        "statement_of_key_benefit": "delivers rugged high-tensile steel cargo deck capacity, best-in-class mileage, and seamless transition options from diesel/CNG to Ape E-City electric",
        "pestle": {"political": 0.65, "economic": 0.80, "social": 0.78, "technological": 0.75, "legal": 0.68, "environmental": 0.75,
            "details": {"political": "Navigates local municipal green zone mandates where metro cities restrict diesel commercial vehicles in favor of CNG and EVs.", "economic": "Crucial driver of micro-logistics for e-commerce deliveries, gas cylinder distribution, and fruit/vegetable wholesale mandi logistics.", "social": "The 'Ape' brand is synonymous with small business entrepreneurship and reliable livelihoods across millions of semi-urban families.", "technological": "Modernized factory with advanced robotics in Baramati, offering fixed and swappable lithium battery variants with smart IoT fleet tracking.", "legal": "Meets BS-VI Stage 2 commercial emissions, stringent RTO safety homologation, and CMVR commercial payload limits.", "environmental": "Promotes clean city logistics by transitioning urban commercial fleets toward zero-tailpipe emission Ape Electrik models."}},
        "porters": {"threat_of_new_entrants": 0.22, "bargaining_power_of_buyers": 0.74, "bargaining_power_of_suppliers": 0.60, "threat_of_substitutes": 0.45, "competitive_rivalry": 0.84,
            "details": {"threat_of_new_entrants": "Low; setting up deep rural 3-wheeler distribution and commercial spare parts availability across India requires immense capital.", "bargaining_power_of_buyers": "High; commercial cargo drivers compare daily earning potential, payload volume, and EMI affordability across competing brands.", "bargaining_power_of_suppliers": "Moderate; established supplier base in Maharashtra automotive hub keeps production costs competitive.", "threat_of_substitutes": "Moderate; small 4-wheel commercial trucks (Tata Ace, Mahindra Jeeto) compete for higher-payload urban cargo routes.", "competitive_rivalry": "Fierce rivalry against market leader Bajaj Auto in passenger 3-wheelers and Mahindra in commercial cargo."}}
    },
    {
        "company": "Matter Motor Works", "sector": "Automotive & Electric Mobility",
        "target_customer": "enthusiastic tech motorcyclists and forward-thinking green commuters",
        "statement_of_need": "seek an authentic geared electric motorcycle experience with manual gear shifting, liquid-cooled battery packs, and futuristic styling",
        "product_name": "Matter AERA 5000", "product_category": "Geared Liquid-Cooled Electric Motorcycles",
        "statement_of_key_benefit": "pioneers India's first 4-speed manual hyper-shift transmission on an electric motorcycle, active liquid-cooled battery and motor, and 7-inch touch display",
        "pestle": {"political": 0.70, "economic": 0.68, "social": 0.80, "technological": 0.90, "legal": 0.64, "environmental": 0.90,
            "details": {"political": "Supported by Gujarat state electronics and clean energy manufacturing policies; aligned with national EV localization guidelines.", "economic": "Targeting performance motorcycle enthusiasts who have resisted electric scooters due to the absence of active clutch and gear shifting engagement.", "social": "Addresses the passionate Indian motorcycling culture that associates gear shifting and engine braking with authentic riding pleasure.", "technological": "Proprietary integrated powertrain featuring liquid-cooled motor, integrated 4-speed gearbox, onboard 5A charger, and 4G Android connected cluster.", "legal": "Certified under AIS-156 safety norms for automotive traction battery systems, patenting indigenous powertrain architectures.", "environmental": "Offers a thrilling, emission-free alternative to 150-200cc petrol streetfighters, utilizing recyclable battery packaging."}},
        "porters": {"threat_of_new_entrants": 0.38, "bargaining_power_of_buyers": 0.68, "bargaining_power_of_suppliers": 0.72, "threat_of_substitutes": 0.50, "competitive_rivalry": 0.80,
            "details": {"threat_of_new_entrants": "Moderate; proprietary geared transmission integration requires deep mechanical and software IP that casual EV assemblers cannot replicate.", "bargaining_power_of_buyers": "Moderate-high; early adopters scrutinize delivery schedules, test ride reviews, and initial showroom network availability.", "bargaining_power_of_suppliers": "High; relies on specialized high-density lithium cells, custom transmission gear forgings, and high-spec TFT touch displays.", "threat_of_substitutes": "High; proven petrol sports motorcycles (Bajaj Pulsar, TVS Apache, Yamaha MT-15) offer immediate reliability and nationwide service.", "competitive_rivalry": "Moderate-high; competing against Revolt Motors, Tork Motors, and upcoming electric motorcycle launches from Ola and Royal Enfield."}}
    },
    {
        "company": "Ultraviolette Automotive", "sector": "Automotive & Electric Mobility",
        "target_customer": "superbike enthusiasts, aerospace technology fans, and high-net-worth performance riders",
        "statement_of_need": "demand track-ready superbike acceleration, aerospace-inspired design, and ultra-high battery capacity without range anxiety",
        "product_name": "Ultraviolette F77 Mach 2", "product_category": "High-Performance Electric Sports Motorcycles",
        "statement_of_key_benefit": "delivers 30 kW peak power, 100 Nm torque, a massive 10.3 kWh battery pack with 323 km IDC range, 3-level traction control, and aerospace-grade aluminum chassis",
        "pestle": {"political": 0.65, "economic": 0.62, "social": 0.82, "technological": 0.95, "legal": 0.65, "environmental": 0.85,
            "details": {"political": "Backed by strategic investments from TVS Motor Company and Zoho, highlighting premier Indian deep-tech hardware engineering capabilities.", "economic": "Commands luxury pricing (₹3-4 lakh+), insulated from entry-level commuter purchasing power downturns by catering to affluent enthusiasts.", "social": "Positioned as India's crown jewel in electric performance, evoking national pride in homegrown aerospace-grade vehicle engineering.", "technological": "Advanced Violette AI operating system, dual-channel Bosch ABS with cornering traction control, regenerative braking, and LTE telematics.", "legal": "Complies with global superbike homologation standards, UNECE European regulations for export markets, and AIS battery safety norms.", "environmental": "Demonstrates that sustainable electric powertrains can outperform high-octane 400cc ICE superbikes with zero tailpipe emissions."}},
        "porters": {"threat_of_new_entrants": 0.28, "bargaining_power_of_buyers": 0.58, "bargaining_power_of_suppliers": 0.70, "threat_of_substitutes": 0.40, "competitive_rivalry": 0.75,
            "details": {"threat_of_new_entrants": "Low; achieving 10 kWh battery safety, rigid trellis chassis dynamics, and aerospace design quality requires exceptional engineering capability.", "bargaining_power_of_buyers": "Moderate; performance riders willing to spend ₹3-4 lakh demand flawless finish quality, track performance, and brand prestige.", "bargaining_power_of_suppliers": "High; requires top-tier tier-1 components including Brembo/Bybre brakes, Pirelli tires, Bosch ECUs, and high-nickel lithium cells.", "threat_of_substitutes": "Moderate; established middleweight petrol superbikes (KTM 390 Duke, Kawasaki Ninja 400) offer proven track capabilities.", "competitive_rivalry": "Low-to-moderate in the electric superbike niche; virtually uncontested in the premium high-performance domestic EV segment."}}
    },
    {
        "company": "Simple Energy", "sector": "Automotive & Electric Mobility",
        "target_customer": "long-distance intercity commuters and suburban daily travelers",
        "statement_of_need": "need extreme single-charge electric scooter range to travel between satellite towns and metro centers without frequent charging stops",
        "product_name": "Simple One Electric Scooter", "product_category": "Ultra-Long Range Electric Scooters",
        "statement_of_key_benefit": "delivers an industry-leading 212 km IDC certified range via a dual battery setup (fixed + portable), 8.5 kW motor, and 72 km/h sprint capability",
        "pestle": {"political": 0.68, "economic": 0.72, "social": 0.78, "technological": 0.88, "legal": 0.65, "environmental": 0.88,
            "details": {"political": "Aligns with Tamil Nadu and Karnataka state electric vehicle policies supporting advanced battery pack R&D and manufacturing plants.", "economic": "Solves range anxiety for suburban commuters who travel 60-80 km daily from peripheral towns to IT corridors, eliminating fuel costs.", "social": "Appeals to pragmatic consumers who value substantial battery capacity and portable battery convenience over pure software gimmicks.", "technological": "In-house developed battery management system, dual-cell architecture with a removable 1.5 kWh pack for home charging, and IP67 thermal potting.", "legal": "Underwent rigorous AIS-156 Amendment 3 thermal shock and nail penetration testing to ensure safety of high-capacity battery packs.", "environmental": "Enables suburban transition to clean mobility, dramatically reducing carbon footprint across peri-urban commuter transit routes."}},
        "porters": {"threat_of_new_entrants": 0.38, "bargaining_power_of_buyers": 0.72, "bargaining_power_of_suppliers": 0.70, "threat_of_substitutes": 0.50, "competitive_rivalry": 0.84,
            "details": {"threat_of_new_entrants": "Moderate; engineering safe 5 kWh battery packs into a compact scooter floorboard presents substantial safety and weight distribution hurdles.", "bargaining_power_of_buyers": "High; customers monitor delivery rollouts closely and easily cross-shop with Ola S1 Pro and Ather 450X.", "bargaining_power_of_suppliers": "Moderate-high; dependent on high-energy-density NMC/LFP battery cells and lightweight alloy castings.", "threat_of_substitutes": "High; 125cc petrol scooters (Suzuki Access, TVS Jupiter 125) provide convenient fuel top-ups for long-distance suburban trips.", "competitive_rivalry": "Fierce; competing directly against market incumbents Ola, Ather, TVS, and Bajaj in premium EV categories."}}
    },
    {
        "company": "Euler Motors", "sector": "Automotive & Electric Mobility",
        "target_customer": "quick commerce operators, courier logistics companies, and e-commerce delivery fleets",
        "statement_of_need": "require heavy-payload commercial electric 3-wheelers capable of continuous multi-shift operation in waterlogged Indian monsoon streets",
        "product_name": "Euler HiLoad EV", "product_category": "Heavy Commercial Electric 3-Wheeler Cargo Trucks",
        "statement_of_key_benefit": "delivers a segment-topping 688 kg payload capacity, liquid-cooled battery pack preventing summer overheating, and 170 km certified range",
        "pestle": {"political": 0.74, "economic": 0.80, "social": 0.75, "technological": 0.88, "legal": 0.68, "environmental": 0.92,
            "details": {"political": "Direct beneficiary of state green delivery mandates, Delhi EV policy requiring commercial delivery fleets to transition to 100% electric.", "economic": "Radically lowers operating cost per delivery to less than ₹0.50 per kilometer, maximizing profit margins for quick commerce hubs.", "social": "Enhances working conditions for commercial delivery drivers through smooth clutch-free driving, zero engine heat, and regenerative braking.", "technological": "Patented liquid-cooled battery pack (ArcReactor) specifically engineered to withstand harsh 45°C+ North Indian summer ambient temperatures.", "legal": "Complies with CMVR cargo volume norms, commercial registration laws, and rigorous AIS battery drop and immersion test standards.", "environmental": "Replaces polluting diesel and petrol delivery vans in dense metropolitan airsheds, operating with zero local carbon emissions."}},
        "porters": {"threat_of_new_entrants": 0.30, "bargaining_power_of_buyers": 0.78, "bargaining_power_of_suppliers": 0.68, "threat_of_substitutes": 0.42, "competitive_rivalry": 0.82,
            "details": {"threat_of_new_entrants": "Moderate-low; commercial B2B fleets require proven thermal endurance, heavy chassis structural validation, and telematics uptime.", "bargaining_power_of_buyers": "High; enterprise fleet procurement leads (Blinkit, Zepto, Flipkart) negotiate massive multi-thousand unit master lease agreements.", "bargaining_power_of_suppliers": "Moderate-high; reliant on high-capacity automotive battery cells and heavy-duty rear axle differential assemblies.", "threat_of_substitutes": "Moderate; traditional 4-wheel mini trucks (Tata Ace, Mahindra Supro) offer higher highway range but at double the operating cost.", "competitive_rivalry": "Intense; competing in commercial EV cargo tenders against Mahindra Last Mile Mobility, Piaggio, and Altigreen."}}
    },
    {
        "company": "Mahindra Last Mile Mobility", "sector": "Automotive & Electric Mobility",
        "target_customer": "urban passenger auto operators and enterprise intra-city logistics hubs",
        "statement_of_need": "demand proven brand reliability, rust-free durable vehicle bodies, and flexible financing for zero-emission last-mile transport",
        "product_name": "Treo & Zor Grand Electric", "product_category": "Advanced Electric Passenger & Cargo 3-Wheelers",
        "statement_of_key_benefit": "features rust-free Sheet Moulding Composite (SMC) modular bodies, IP67 waterproof powertrains, and wide pan-India Mahindra dealership backing",
        "pestle": {"political": 0.72, "economic": 0.82, "social": 0.82, "technological": 0.80, "legal": 0.68, "environmental": 0.92,
            "details": {"political": "Actively participates in PM E-DRIVE and FAME subsidy disbursement, working closely with municipal transport boards across metro corridors.", "economic": "Provides lucrative livelihood economics with guaranteed fuel cost savings of over ₹60,000 annually compared to fossil fuel auto-rickshaws.", "social": "Deep brand trust associated with the Mahindra badge ensures pride of ownership and high trade-in valuation for auto drivers.", "technological": "Advanced modular composite body panels that never rust or dent, coupled with telematics-driven remote diagnostics and battery health monitoring.", "legal": "Meets stringent RTO regulatory norms for commercial public conveyance vehicles and central safety standards.", "environmental": "Market leader in domestic electric 3-wheelers, eliminating millions of tons of urban carbon emissions across 400+ Indian cities."}},
        "porters": {"threat_of_new_entrants": 0.22, "bargaining_power_of_buyers": 0.76, "bargaining_power_of_suppliers": 0.58, "threat_of_substitutes": 0.45, "competitive_rivalry": 0.84,
            "details": {"threat_of_new_entrants": "Low; Mahindra's massive commercial vehicle manufacturing plants, vendor network, and Mahindra Finance credit reach create deep moats.", "bargaining_power_of_buyers": "High; auto drivers evaluate battery warranty terms, real-world passenger range with full load, and monthly installment amounts.", "bargaining_power_of_suppliers": "Moderate; strong bargaining leverage over Tier-1 component makers and localized motor/controller fabricators.", "threat_of_substitutes": "Moderate; traditional Bajaj CNG auto-rickshaws remain deeply entrenched in cities with dense gas station networks.", "competitive_rivalry": "Fierce battle for market leadership against Bajaj RE Electric, Piaggio Ape Electrik, and Euler Motors."}}
    }
]

print(f"Sector 1 populated: {len(SECTORS_01_06)} companies")
